spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration


spring.thymeleaf.prefix=classpath:/templates/

server.port=8080
naver.client-id=6bnsim6dr6
naver.client-secret=CfUGvQrEPjdbMoswJPwjgl9x3I801eRr3yvK2MAg